name: Build and Push Docker Image
on:
  push:
    branches:
      - main  
env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the version of Node.js you need

    - name: Login to Docker Hub
      run: echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USERNAME} --password-stdin
     
    - name: Use Docker Buildx Default Builder
      run: docker buildx use default

    - name: Build Docker Image
      run: docker build -t ${DOCKER_USERNAME}/store-api:latest .

    - name: Push Docker Image
      run: docker push ${DOCKER_USERNAME}/store-api:latest

    - name: Cleanup
      run: docker logout

