POST https://stratego2023.duckdns.org:2002/stratego-api/myApi?key=firstTest
Content-Type: application/json

{
  "Item1": "Cool hike",
  "location": "maple canyon"
}

GET https://stratego2023.duckdns.org:2002/stratego-api/myApi?key=firstTest
