POST https://100.68.122.57:2002/stratego-api?key=bregibson7
Content-Type: application/json

{
  "Item1": "Cool hike",
  "location": "maple canyon"
}

###
GET https://100.68.122.57:2002/stratego-api/user?key=bre.gibson7

###
GET https://100.68.122.57:2002/stratego-api/default?key=testBoard