version: '3'
services:
  web-keycloak-strat:
    image: bitnami/keycloak
    container_name: web-keycloak-strat
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_HOST=database-keycloak-strat
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=as;ldkfja;slfnesfanseoccvm,dfirenreuif

  database-keycloak-strat:
    image: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=as;ldkfja;slfnesfanseoccvm,dfirenreuif
      - POSTGRES_DB=keycloak
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data

  swag-keycloak:
    image: lscr.io/linuxserver/swag
    container_name: swag_keycloak
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=startegokeycloak.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
      - /home/stratego/data/keycloakswag:/config
    ports:
    - 0.0.0.0:2004:443

    