version: "3"
services:
  client:
    build: .
    restart: unless-stopped
    mem_limit: 512M

  stratego-api:
    build: ../stratego-api
    restart: unless-stopped
    container_name: stratego-api
    volumes:
      - /home/stratego/data/apiStorage:/app/storage 
  
  swag:
    image: lscr.io/linuxserver/swag
    container_name: stratego
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=stratego2023.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
      - /home/stratego/data/strategoswag:/config

    ports:
    - 0.0.0.0:2002:443 

 