name: Update home server containers
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push, workflow_dispatch]
jobs:
  deploy-stratego:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd stratego-front
          
          docker compose build --no-cache 
          docker build -t breanna_lint -f lint.Dockerfile .
          docker run -i --rm breanna_lint
      
          docker compose pull
          docker compose build 
          docker compose down
          docker compose up -d

  deploy-keycloak:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd keycloak
          docker build 

          docker compose pull
          docker compose build 
          docker compose down
          docker compose up -d