name: Update home server containers
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          docker build -t breanna_lint -f lint.Dockerfile .
          docker run -i --rm breanna_lint
          ls
          docker compose pull
          docker compose build --no-cache
          docker compose down
          docker compose up -d